#!/usr/bin/env bash
# =============================================================================
# 03-shell-environment.sh - Automatic Dev Setup
# Purpose: Configure Zsh environment, Oh My Zsh, powerlevel10k, plugins, aliases, and functions.
# Version: 3.0.0
# Dependencies: bash, git, curl, zsh
# Criticality: ALPHA
# =============================================================================

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_PATH="$(readlink -f "$0" 2>/dev/null || perl -MCwd=abs_path -le 'print abs_path($ARGV[0])' "$0")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"


source "$(dirname "${BASH_SOURCE[0]}")/../lib/automatic-dev-env.sh"

ads_enable_traps
export ADS_FAILURE_CODE="${ADS_FAILURE_CODE:-ADS-M03}"

OMZ_INSTALL_DIR="${ZSH:-$HOME/.oh-my-zsh}"
ZSH_CUSTOM="${ZSH_CUSTOM:-${OMZ_INSTALL_DIR}/custom}"
POWERLEVEL10K_DIR="${ZSH_CUSTOM}/themes/powerlevel10k"
MODE="${ADS_MODE:-standard}"

ensure_default_shell() {
    if [[ "$SHELL" != "/bin/zsh" ]]; then
        log_info "Setting default shell to /bin/zsh (requires password)..."
        ads_require_sudo
        chsh -s /bin/zsh "$USER"
    else
        log_success "Zsh already set as default shell."
    fi
}

install_oh_my_zsh() {
    if [[ -d "$OMZ_INSTALL_DIR" ]]; then
        log_success "Oh My Zsh already installed."
        return 0
    fi
    log_info "Installing Oh My Zsh..."
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

install_powerlevel10k() {
    if [[ -d "$POWERLEVEL10K_DIR" ]]; then
        log_success "powerlevel10k already installed."
        return 0
    fi
    log_info "Installing powerlevel10k theme..."
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$POWERLEVEL10K_DIR"
}

ensure_plugin() {
    local repo_url="$1"
    local target_dir="$2"
    if [[ -d "$target_dir/.git" ]]; then
        log_debug "Updating plugin $(basename "$target_dir")"
        git -C "$target_dir" pull --ff-only >/dev/null || log_warning "Failed to update $(basename "$target_dir")"
    elif [[ -d "$target_dir" ]]; then
        log_debug "Plugin directory exists: $target_dir"
    else
        log_info "Installing plugin $(basename "$target_dir")"
        git clone --depth=1 "$repo_url" "$target_dir"
    fi
}

install_plugins() {
    ensure_plugin "https://github.com/zsh-users/zsh-autosuggestions" "${ZSH_CUSTOM}/plugins/zsh-autosuggestions"
    ensure_plugin "https://github.com/zsh-users/zsh-syntax-highlighting" "${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting"
    ensure_plugin "https://github.com/zsh-users/zsh-completions" "${ZSH_CUSTOM}/plugins/zsh-completions"
    ensure_plugin "https://github.com/unixorn/fzf-zsh-plugin" "${ZSH_CUSTOM}/plugins/fzf-zsh-plugin"
}

write_zshrc() {
    local zshrc="$HOME/.zshrc"
    ads_backup_file "$zshrc"
    
    log_info "Writing comprehensive .zshrc configuration..."
    cat > "$zshrc" <<'EOF'
# =============================================================================
# ~/.zshrc - Interactive shell configuration for zsh
# Generated by Automatic Dev Setup
# =============================================================================

# -----------------------------------------------------------------------------
# Core Shell Settings
# -----------------------------------------------------------------------------
export ZDOTDIR="$HOME"
export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"
export DISABLE_COMPFIX="true"
export ZSH="${HOME}/.oh-my-zsh"
export ZSH_CACHE_DIR="${ZSH}/cache"

# -----------------------------------------------------------------------------
# Homebrew Environment
# -----------------------------------------------------------------------------
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# -----------------------------------------------------------------------------
# Cargo/Rust Environment
# -----------------------------------------------------------------------------
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# -----------------------------------------------------------------------------
# Shell Completions (with daily cache)
# -----------------------------------------------------------------------------
autoload -Uz compinit
COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump"
if [[ ! -d "${ZSH_CACHE_DIR}" ]]; then
  mkdir -p "${ZSH_CACHE_DIR}"
fi
if [[ ! -f "${COMPDUMP}" || $(find "${COMPDUMP}" -mtime +1 -print -quit) ]]; then
  compinit
  touch "${COMPDUMP}"
else
  compinit -C
fi

ZSH_THEME="powerlevel10k/powerlevel10k"

typeset -a plugins
plugins=(
  git docker docker-compose kubectl terraform aws python pip pyenv node npm yarn rust cargo go ruby rails bundler vscode
  zsh-autosuggestions zsh-completions fzf direnv zsh-syntax-highlighting
)

source "${ZSH}/oh-my-zsh.sh"

# Ensure zsh-syntax-highlighting is always loaded last for correctness.
if [[ -f "${ZSH_CUSTOM:-${ZSH}/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "${ZSH_CUSTOM:-${ZSH}/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# Load Powerlevel10k configuration if present
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Environment variables
export EDITOR='nvim'
export VISUAL='code --wait'
export BROWSER='google-chrome'
export TERMINAL='warp'
export PAGER='bat'
export AUTOMATIC_DEV_HOME="$HOME/automatic_dev_setup"
export PROJECTS_DIR="${HOME}/__github_repo/projects"
export PROJECTS_DIR="$CODE_DIR/projects"
export ADS_CACHE_HOME="$HOME/.automatic_dev_setup"
export GEM_HOME="$HOME/.gem"
export GOPATH="$HOME/go"
export NVM_DIR="$HOME/.nvm"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="$GEM_HOME/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$AUTOMATIC_DEV_HOME/bin:$PATH"
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export PIP_REQUIRE_VIRTUALENV=true
export PIP_DISABLE_PIP_VERSION_CHECK=1
export TF_CPP_MIN_LOG_LEVEL=2
export CUDA_VISIBLE_DEVICES=""
export NODE_ENV=development
export RUST_BACKTRACE=1
export GO111MODULE=on
export CARGO_NET_GIT_FETCH_WITH_CLI=true
export ARCHFLAGS="-arch arm64"
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"

# Modern CLI aliases
alias ll='eza -la --git --header --icons --time-style=long-iso'
alias ls='eza --icons'
alias la='eza -la --icons'
alias tree='eza --tree --icons --level=3'
alias cat='bat --style=auto --paging=never'
alias grep='rg'
alias find='fd'
alias du='dust'
alias df='duf'
alias ps='procs'
alias top='btop'
alias htop='btop'
alias ping='gping'
alias dig='doggo'

# Git workflow aliases
alias g='git'
alias gs='git status --short --branch'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit --verbose'
alias gcm='git commit --message'
alias gca='git commit --all --verbose'
alias gcam='git commit --all --message'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gl='git pull --rebase --autostash'
alias gd='git diff'
alias gdc='git diff --cached'
alias gb='git branch'
alias gba='git branch --all'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gm='git merge --no-ff'
alias gr='git rebase --interactive'
alias glog='git log --oneline --graph --decorate --all --max-count=20'
alias gloga='git log --oneline --graph --decorate --all'
alias gst='git stash'
alias gstp='git stash pop'
alias gstl='git stash list'
alias lg='lazygit'
alias gg='git gui'
alias gitk='gitk --all'

# Python & data science
alias py='python3'
alias python='python3'
alias pip='pip3'
alias pip-upgrade='pip list --outdated --format=freeze | grep -v "^-e" | cut -d = -f 1 | xargs -n1 pip install -U'
alias jl='jupyter lab'
alias jn='jupyter notebook'
alias js='jupyter server list'
alias jk='jupyter kernelspec list'

# Development workflow aliases
alias code='code .'
alias c='code .'
alias vim='nvim'
alias vi='nvim'
alias e='$EDITOR'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'
alias cdcode='cd ~/__github_repo'
alias cdproj='cd ~/__github_repo'
alias cdtemplates='cd ~/__github_repo/__project_templates'
alias cdads='cd ~/automatic_dev_setup'
alias cddl='cd ~/Downloads'
alias cddt='cd ~/Desktop'
alias cddoc='cd ~/Documents'

# Docker aliases
alias d='docker'
alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcr='docker-compose restart'
alias dcl='docker-compose logs'
alias dcp='docker-compose pull'
alias dps='docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
alias dpsa='docker ps --all --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
alias di='docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}\t{{.CreatedSince}}"'
alias dclean='docker system prune --all --force'
alias dstop='docker stop $(docker ps -q)'
alias drm='docker rm $(docker ps -aq)'
alias drmi='docker rmi $(docker images -q)'

# Database aliases
alias pgstart='brew services start postgresql@16'
alias pgstop='brew services stop postgresql@16'
alias pgrestart='brew services restart postgresql@16'
alias pgstatus='brew services list | grep postgresql'
alias pgcli='psql -d postgres'
alias pguser='createuser --interactive'
alias pgdb='createdb'
alias redisstart='brew services start redis'
alias redisstop='brew services stop redis'
alias redisrestart='brew services restart redis'
alias rediscli='redis-cli'
alias redisflush='redis-cli FLUSHALL'
alias mongostart='brew services start mongodb-community@7.0'
alias mongostop='brew services stop mongodb-community@7.0'
alias mongorestart='brew services restart mongodb-community@7.0'
alias mongocli='mongosh'

# System maintenance
alias brewup='brew update && brew upgrade && brew cleanup && brew doctor'
alias pipup='pip list --outdated --format=freeze | grep -v "^-e" | cut -d = -f 1 | xargs -n1 pip install -U'
alias npmup='npm update -g'
alias rustup-update='rustup update'
alias gemup='gem update && gem cleanup'
alias sysup='sudo softwareupdate --install --all'
alias fullup='brewup && pipup && npmup && rustup-update && gemup && sysup'
alias ports='lsof -i -P -n | grep LISTEN'
alias myip='curl -s https://httpbin.org/ip | jq -r .origin'
alias localip='ipconfig getifaddr en0'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -'
alias diskusage='df -h | grep -E "^/dev/"'
alias meminfo='vm_stat | head -10'
alias cleanup='sudo periodic daily weekly monthly'
alias emptytrash='sudo rm -rfv ~/.Trash'
alias cleands='find . -type f -name "*.DS_Store" -ls -delete'
alias cleanupbrew='brew cleanup --prune-prefix && brew autoremove'

# Utility functions
mkcd() {
  if [[ $# -ne 1 ]]; then
    echo "Usage: mkcd <directory>"
    return 1
  fi
  mkdir -p "$1" && cd "$1"
}

extract() {
  if [[ ! -f "$1" ]]; then
    echo "Error: '$1' is not a valid file"
    return 1
  fi
  case "$1" in
    *.tar.bz2) tar xjf "$1" ;;
    *.tar.gz) tar xzf "$1" ;;
    *.bz2) bunzip2 "$1" ;;
    *.rar) if command -v unar >/dev/null 2>&1; then unar "$1"; else echo "Install 'unar' to extract RAR archives"; return 1; fi ;;
    *.gz) gunzip "$1" ;;
    *.tar) tar xf "$1" ;;
    *.tbz2) tar xjf "$1" ;;
    *.tgz) tar xzf "$1" ;;
    *.zip) unzip "$1" ;;
    *.Z) uncompress "$1" ;;
    *.7z) 7z x "$1" ;;
    *) echo "Error: '$1' cannot be extracted via extract()" ;;
  esac
}

killport() {
  if [[ $# -ne 1 ]]; then
    echo "Usage: killport <port>"
    return 1
  fi
  local pid
  pid=$(lsof -ti:$1)
  if [[ -n "$pid" ]]; then
    kill -9 "$pid"
    echo "Killed process on port $1"
  else
    echo "No process found on port $1"
  fi
}

venv() {
  local venv_paths=("venv" ".venv" "env" ".env")
  for path in "${venv_paths[@]}"; do
    if [[ -d "$path" && -f "$path/bin/activate" ]]; then
      source "$path/bin/activate"
      echo "Activated virtual environment: $path"
      return 0
    fi
  done
  echo "No virtual environment found in current directory"
  return 1
}

new_python_project() {
  if [[ $# -lt 1 ]]; then
    echo "Usage: new_python_project <name> [type]"
    return 1
  fi
  local name="$1"
  local type="${2:-basic}"
  local project_dir="$PROJECTS_DIR/$name"
  mkdir -p "$project_dir"
  cd "$project_dir"
  python3 -m venv venv
  case "$type" in
    basic)
      echo "# $name" > README.md
      echo "venv/" > .gitignore
      mkdir -p src tests
      ;;
    ml)
      mkdir -p {data,models,notebooks,src,results}
      ;;
    web)
      mkdir -p {app,templates,static,tests}
      echo "flask>=2.0" > requirements.txt
      ;;
    automatic-dev)
      mkdir -p {data,notebooks,src,results}
      ;;
  esac
  source venv/bin/activate
  pip install --upgrade pip setuptools wheel
  [[ -f requirements.txt ]] && pip install -r requirements.txt
  git init
  echo "Project '$name' created in $project_dir"
}

sysinfo() {
  echo "========== System Information =========="
  echo "OS: $(sw_vers -productName) $(sw_vers -productVersion) ($(sw_vers -buildVersion))"
  echo "Architecture: $(uname -m)"
  echo "Kernel: $(uname -r)"
  echo "Shell: $SHELL"
  echo "Terminal: $TERM_PROGRAM"
  echo ""
  echo "========== Hardware Information ========"
  echo "CPU: $(sysctl -n machdep.cpu.brand_string)"
  echo "CPU Cores: $(sysctl -n hw.ncpu)"
  echo "Memory: $(echo "$(sysctl -n hw.memsize) / 1024 / 1024 / 1024" | bc)GB"
  echo ""
  echo "========== Development Tools ==========="
  command -v python3 >/dev/null && echo "Python: $(python3 --version)"
  command -v node >/dev/null && echo "Node.js: $(node --version)"
  command -v go >/dev/null && echo "Go: $(go version | awk '{print $3}')"
  command -v rustc >/dev/null && echo "Rust: $(rustc --version | awk '{print $2}')"
  command -v git >/dev/null && echo "Git: $(git --version | awk '{print $3}')"
  command -v docker >/dev/null && echo "Docker: $(docker --version | awk '{print $3}' | tr -d ',')"
  echo ""
  echo "========== Python Environment =========="
  [[ -n "$VIRTUAL_ENV" ]] && echo "Active venv: $VIRTUAL_ENV" || echo "No active virtual environment"
  command -v python3 >/dev/null && echo "Python location: $(command -v python3)"
  command -v pip3 >/dev/null && echo "Pip location: $(command -v pip3)"
}

tfcheck() {
python3 - <<'PYEOF'
import os, sys
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
try:
    import tensorflow as tf
    print(f"TensorFlow version: {tf.__version__}")
    devices = tf.config.list_physical_devices()
    print(f"Physical devices: {len(devices)}")
    for device in devices:
        print(f"  - {device}")
    gpus = tf.config.list_physical_devices('GPU')
    print(f"GPU (MPS) devices: {len(gpus)}")
    device_to_use = '/GPU:0' if gpus else '/CPU:0'
    with tf.device(device_to_use):
        a = tf.constant([1.0, 2.0, 3.0])
        result = tf.reduce_sum(a).numpy()
        if result == 6.0:
            print("Test computation successful: 6.0")
        else:
            print(f"Test computation FAILED. Expected 6.0 got {result}")
            sys.exit(1)
except ImportError:
    print("TensorFlow not installed")
    sys.exit(1)
except Exception as exc:
    print(f"TensorFlow error: {exc}")
    sys.exit(1)
PYEOF
}

torchcheck() {
python3 - <<'PYEOF'
import sys
try:
    import torch
    print(f"PyTorch version: {torch.__version__}")
    has_mps = hasattr(torch.backends, 'mps') and torch.backends.mps.is_available()
    if hasattr(torch.backends, 'mps'):
        print(f"MPS available: {has_mps}")
        print(f"MPS built: {torch.backends.mps.is_built()}")
    device = "mps" if has_mps else "cpu"
    a = torch.tensor([1.0, 2.0, 3.0], device=device)
    result = torch.sum(a).item()
    if result == 6.0:
        print("Test computation successful: 6.0")
    else:
        print(f"Test computation FAILED. Expected 6.0 got {result}")
        sys.exit(1)
except ImportError:
    print("PyTorch not installed")
    sys.exit(1)
except Exception as exc:
    print(f"PyTorch error: {exc}")
    sys.exit(1)
PYEOF
}

db_service() {
  if [[ $# -lt 2 ]]; then
    echo "Usage: db_service {start|stop|restart|status} {postgres|redis|mongo|all}"
    return 1
  }
  local action="$1"
  local service="$2"
  local services=()
  case "$service" in
    postgres|pg) services=("postgresql@16") ;;
    redis) services=("redis") ;;
    mongo|mongodb) services=("mongodb-community@7.0") ;;
    all) services=("postgresql@16" "redis" "mongodb-community@7.0") ;;
    *)
      echo "Usage: db_service {start|stop|restart|status} {postgres|redis|mongo|all}"
      return 1
      ;;
  esac

  if [[ "$action" == "status" ]]; then
    brew services list | grep -E "(postgresql|redis|mongodb)"
    return 0
  fi

  for svc in "${services[@]}"; do
    brew services "$action" "$svc"
  done
}

alias dbstart='db_service start all'
alias dbstop='db_service stop all'
alias dbrestart='db_service restart all'
alias dbstatus='brew services list | grep -E "(postgresql|redis|mongodb)"'

export PROMPT_EOL_MARK=""

# -----------------------------------------------------------------------------
# Pyenv Configuration
# -----------------------------------------------------------------------------
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init - zsh)"
fi
EOF

    if [[ "$MODE" == "performance" ]]; then
        cat >> "$zshrc" <<'EOF'

# -----------------------------------------------------------------------------
# Performance Mode Optimizations
# -----------------------------------------------------------------------------
export ZSH_AUTOSUGGEST_USE_ASYNC=1
export HISTSIZE=50000
export SAVEHIST=50000
export POWERLEVEL9K_DISABLE_RPROMPT=true
setopt SHARE_HISTORY
EOF
    fi
}

write_zprofile() {
    local zprofile="$HOME/.zprofile"
    ads_backup_file "$zprofile"
    
    log_info "Writing structured .zprofile configuration..."
    cat > "$zprofile" <<'EOF'
# =============================================================================
# ~/.zprofile - Login shell configuration for zsh
# Loaded once per login session before .zshrc
# Generated by Automatic Dev Setup
# =============================================================================

# -----------------------------------------------------------------------------
# Core Environment
# -----------------------------------------------------------------------------
export ZDOTDIR="$HOME"
export SHELL="/bin/zsh"

# -----------------------------------------------------------------------------
# Homebrew Environment (early initialization for login shells)
# -----------------------------------------------------------------------------
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# -----------------------------------------------------------------------------
# Development Tool Paths
# -----------------------------------------------------------------------------

# Python/Pyenv
export PYENV_ROOT="$HOME/.pyenv"
if [[ -d "$PYENV_ROOT/bin" ]]; then
  export PATH="$PYENV_ROOT/bin:$PATH"
fi
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# Rust/Cargo
export CARGO_HOME="$HOME/.cargo"
if [[ -d "$CARGO_HOME/bin" ]]; then
  export PATH="$CARGO_HOME/bin:$PATH"
fi
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Go
export GOPATH="$HOME/go"
export GOROOT="$(brew --prefix golang 2>/dev/null || echo '/usr/local/go')"
if [[ -d "$GOPATH/bin" ]]; then
  export PATH="$GOPATH/bin:$PATH"
fi

# Ruby/Gem
export GEM_HOME="$HOME/.gem"
if [[ -d "$GEM_HOME/bin" ]]; then
  export PATH="$GEM_HOME/bin:$PATH"
fi

# Node/NVM
export NVM_DIR="$HOME/.nvm"

# -----------------------------------------------------------------------------
# User-specific Paths
# -----------------------------------------------------------------------------

# Local binaries (pipx and user installations)
export PATH="$HOME/.local/bin:$PATH"

# Automatic Dev Setup
export AUTOMATIC_DEV_HOME="$HOME/automatic_dev_setup"
if [[ -d "$AUTOMATIC_DEV_HOME/bin" ]]; then
  export PATH="$AUTOMATIC_DEV_HOME/bin:$PATH"
fi

# Project directories
export CODE_DIR="$HOME/__github_repo"
export PROJECTS_DIR="$CODE_DIR/projects"
export ADS_CACHE_HOME="$HOME/.automatic_dev_setup"

# -----------------------------------------------------------------------------
# System Architecture Flags (Apple Silicon optimisation)
# -----------------------------------------------------------------------------
export ARCHFLAGS="-arch arm64"
export CPPFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"

# -----------------------------------------------------------------------------
# Security and Privacy Settings
# -----------------------------------------------------------------------------
export HOMEBREW_NO_ANALYTICS=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"
EOF
}

write_profile() {
    local profile="$HOME/.profile"
    ads_backup_file "$profile"
    
    log_info "Writing POSIX-compliant .profile configuration..."
    cat > "$profile" <<'EOF'
# =============================================================================
# ~/.profile - POSIX-compliant shell configuration
# Loaded by sh/bash/dash and sourced by zsh when no .zprofile exists
# Generated by Automatic Dev Setup
# =============================================================================

# -----------------------------------------------------------------------------
# Core Environment Variables
# -----------------------------------------------------------------------------
export HOME="${HOME:-/Users/$(whoami)}"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# -----------------------------------------------------------------------------
# Default Programs
# -----------------------------------------------------------------------------
export EDITOR="nvim"
export VISUAL="code --wait"
export PAGER="less"
export BROWSER="open"

# -----------------------------------------------------------------------------
# XDG Base Directory Specification
# -----------------------------------------------------------------------------
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# -----------------------------------------------------------------------------
# Development Environments (POSIX-compatible)
# -----------------------------------------------------------------------------

# Python/Pyenv
export PYENV_ROOT="${HOME}/.pyenv"
if [ -d "${PYENV_ROOT}/bin" ]; then
  export PATH="${PYENV_ROOT}/bin:${PATH}"
fi
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# Rust/Cargo
export CARGO_HOME="${HOME}/.cargo"
if [ -f "${HOME}/.cargo/env" ]; then
  . "${HOME}/.cargo/env"
fi

# Go
export GOPATH="${HOME}/go"
if [ -d "${GOPATH}/bin" ]; then
  export PATH="${GOPATH}/bin:${PATH}"
fi

# Ruby/Gem
export GEM_HOME="${HOME}/.gem"
if [ -d "${GEM_HOME}/bin" ]; then
  export PATH="${GEM_HOME}/bin:${PATH}"
fi

# Node Version Manager
export NVM_DIR="${HOME}/.nvm"

# -----------------------------------------------------------------------------
# User Paths
# -----------------------------------------------------------------------------

# Local binaries
if [ -d "${HOME}/.local/bin" ]; then
  export PATH="${HOME}/.local/bin:${PATH}"
fi

# Homebrew (macOS)
if [ -x "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x "/usr/local/bin/brew" ]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Workspace directories
export CODE_DIR="${HOME}/__github_repo"
export PROJECTS_DIR="${CODE_DIR}/projects"
export AUTOMATIC_DEV_HOME="${HOME}/automatic_dev_setup"

# Add Automatic Dev Setup binaries to PATH
if [ -d "${AUTOMATIC_DEV_HOME}/bin" ]; then
  export PATH="${AUTOMATIC_DEV_HOME}/bin:${PATH}"
fi

# -----------------------------------------------------------------------------
# Development Settings
# -----------------------------------------------------------------------------

# Python
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export PIP_REQUIRE_VIRTUALENV=false
export PIP_DISABLE_PIP_VERSION_CHECK=1

# Node.js
export NODE_ENV="development"

# Rust
export RUST_BACKTRACE=1
export CARGO_NET_GIT_FETCH_WITH_CLI=true

# Go
export GO111MODULE=on

# -----------------------------------------------------------------------------
# System Settings
# -----------------------------------------------------------------------------

# History
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL="ignoreboth:erasedups"

# Security
export HOMEBREW_NO_ANALYTICS=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# macOS specific
if [ "$(uname)" = "Darwin" ]; then
  export ARCHFLAGS="-arch arm64"
  export CPPFLAGS="-I/opt/homebrew/include"
  export LDFLAGS="-L/opt/homebrew/lib"
fi

# -----------------------------------------------------------------------------
# SSH Agent (if not already running)
# -----------------------------------------------------------------------------
if [ -z "${SSH_AUTH_SOCK}" ]; then
  if [ -f "${HOME}/.ssh/id_ed25519" ] || [ -f "${HOME}/.ssh/id_rsa" ]; then
    eval "$(ssh-agent -s)" >/dev/null 2>&1
    ssh-add >/dev/null 2>&1
  fi
fi

# -----------------------------------------------------------------------------
# Load shell-specific configuration if available
# -----------------------------------------------------------------------------
if [ -n "${BASH_VERSION}" ] && [ -f "${HOME}/.bashrc" ]; then
  . "${HOME}/.bashrc"
fi
EOF
}

create_shell_config_documentation() {
    local dev_home="${AUTOMATIC_DEV_HOME:-$HOME/automatic_dev_setup}"
    local doc_path="${dev_home}/docs"
    mkdir -p "$doc_path"
    
    log_info "Creating shell configuration documentation..."
    cat > "$doc_path/SHELL_CONFIGURATION.md" <<'EOF'
# Shell Configuration Documentation

## Overview
This document describes the shell configuration files managed by Automatic Dev Setup.

## File Hierarchy

### Loading Order
- **Login Shell:** /etc/profile → ~/.profile → ~/.zprofile → ~/.zshrc
- **Interactive Shell:** ~/.zshrc only
- **Non-interactive:** No configuration files loaded

### File Purposes

#### ~/.profile
- POSIX-compliant configuration
- Works across all shells (sh, bash, dash, zsh)
- Contains universal environment variables
- Manages development tool paths

#### ~/.zprofile
- Zsh-specific login shell configuration
- Loaded once per login session
- Contains PATH modifications and tool initializations
- Architecture-specific settings (Apple Silicon)

#### ~/.zshrc  
- Interactive zsh configuration only
- Contains aliases, functions, and completions
- Oh-My-Zsh and theme configuration
- Interactive tool features

## Customization

To add custom configurations:
1. Environment variables → Add to ~/.zprofile
2. Aliases/Functions → Add to ~/.zshrc
3. Cross-shell settings → Add to ~/.profile

## Troubleshooting

### Check configuration loading:
```bash
zsh -xl  # Login shell with trace
zsh -x   # Interactive shell with trace
```

### Verify PATH:
```bash
echo $PATH | tr ':' '\n' | nl
```

### Profile startup time:
```bash
time zsh -i -c exit
```

## Maintenance

The configuration files are automatically backed up before modification.
Backups are stored with .backup-TIMESTAMP extension.

To restore a backup:
```bash
cp ~/.zshrc.backup-* ~/.zshrc
```
EOF
}

main() {
    log_header "[03] Shell Environment"
    ensure_default_shell
    install_oh_my_zsh
    install_powerlevel10k
    install_plugins
    write_profile
    write_zprofile
    write_zshrc
    create_shell_config_documentation
    log_success "Shell environment fully configured with structured configuration files."
}

main "$@"
